<?php

return [
    "Alagoas" => [
        "Barra de Sao Miguel",
        "Coruripe",
        "Feliz Deserto",
        "Marechal Deodoro",
        "Maragogi",
        "Maceio",
        "Passo de Camaragibe",
        "Porto de Pedras",
        "Roteiro",
        "Sao Miguel dos Milagres"
    ],
    "Amapa" => [
        "Amapa",
        "Calcione",
        "Macapa",
        "Oiapoque"
    ],
    "Ceara" => [
        "Amontada",
        "Aracati",
        "Caucaia",
        "Itapipoca",
        "Itarema",
        "Sao Goncalo do Amarante"
    ],
    "Espirito Santo" => [
        "Anchieta",
        "Aracruz",
        "Conceicao da Barra",
        "Fundao",
        "Guarapari",
        "Itapemirim",
        "Linhares",
        "Marataizes",
        "Piuma",
        "Presidente Kennedy",
        "Rio de Janeiro",
        "Sao Mateus",
        "Serra",
        "Vila Velha",
        "Vitoria"
    ],
    "Maranhao" => [
        "Axixa",
        "Bacari",
        "Bacurituba",
        "Cajapio",
        "Candido Mendes",
        "Godofredo Viana",
        "Porto Rico do Maranhao",
        "Primeira Cruz",
        "Raposa",
        "Rosario",
        "Sao Joao Batista",
        "Sao Luis",
        "Sao Jose de Ribamar",
        "Serrano do Maranhao",
        "Tutoia"
    ],
    "Minas Gerais" => [
        "Belo Horizonte",
        "Contagem",
        "Juiz de Fora",
        "Uberlandia",
        "Betim",
        "Montes Claros",
        "Ribeirao das Neves",
        "Governador Valadares",
        "Ipatinga",
        "Uberaba"
    ],
    "Mato Grosso do Sul" => [
        "Campo Grande",
        "Dourados",
        "Tres Lagoas",
        "Corumba",
        "Ponta Pora",
        "Rio Verde de Mato Grosso"
    ],
    "Mato Grosso" => [
        "Cuiaba",
        "Varzea Grande",
        "Rondonopolis",
        "Sinop",
        "Lucas do Rio Verde",
        "Caceres",
        "Tangara da Serra"
    ],
    "Para" => [
        "Belem",
        "Ananindeua",
        "Maraba",
        "Parauapebas",
        "Santarem",
        "Castanhal",
        "Barcarena",
        "Cameta",
        "Altamira"
    ],
    "Paraiba" => [
        "Cabedelo",
        "Conde",
        "Joao Pessoa",
        "Lucena",
        "Pitimbu",
        "Rio Tinto"
    ],
    "Pernambuco" => [
        "Barreiros",
        "Cabo de Santo Agostinho",
        "Fernando de Noronha",
        "Igarassu",
        "Jaboatao dos Guararapes",
        "Olinda",
        "Paulista",
        "Recife",
        "Sao Jose da Coroa Grande"
    ],
    "Piaui" => [
        "Cajueiro da Praia",
        "Ilha Grande",
        "Parnaiba"
    ],
    "Parana" => [
        "Guaraquecaba",
        "Matinhos",
        "Parangua"
    ],
    "Rio de Janeiro" => [
        "Angra dos Reis",
        "Araruama",
        "Armacao dos Buzios",
        "Arraial do Cabo",
        "Cabo Frio",
        "Carapebus",
        "Duque de Caxias",
        "Guapimirim",
        "Itaborai",
        "Itaguai",
        "Mage",
        "Macae",
        "Mangaratiba",
        "Marica",
        "Paraty",
        "Rio das Ostras",
        "Rio de Janeiro",
        "Saquarema",
        "Sao Francisco de Itabapoana",
        "Sao Goncalo",
        "Sao Joao da Barra",
        "Sao Joao da Barra",
        "Quissama"
    ],
    "Rio Grande do Norte" => [
        "Areia Branca",
        "Baia Formosa",
        "Canguaretama",
        "Ceara-Mirim",
        "Extremoz",
        "Galinhos",
        "Grossos",
        "Guamare",
        "Macau",
        "Maxaranguape",
        "Nisia Floresta",
        "Parnamirim",
        "Porto do Mangue",
        "Rio do Fogo",
        "Senador Georgino Avelino",
        "Tibau",
        "Tibau do Sul",
        "Touros",
        "Sao Miguel do Gostoso"
    ],
    "Rondonia" => [
        "Porto Velho",
        "Ji-Parana",
        "Ariquemes",
        "Cacoal",
        "Rolim de Moura"
    ],
    "Rio Grande do Sul" => [
        "Capao da Canoa",
        "Cidreira",
        "Imbe",
        "Osorio",
        "Rio Grande",
        "Santa Vitoria do Palmar",
        "Sao Jose do Norte",
        "Tavares",
        "Torres",
        "Tramandai"
    ],
    "Santa Catarina" => [
        "Araquari",
        "Balneario Arroio do Silva",
        "Balneario Barra do Sul",
        "Balneario Camboriu",
        "Balneario Gaivota",
        "Balneario Piccarras",
        "Balneario Rincao",
        "Bombinhas",
        "Florianopolis",
        "Garopaba",
        "Governador Celso Ramos",
        "Imbituba",
        "Itajai",
        "Itapoa",
        "Itapema",
        "Jaguaruna",
        "Laguna",
        "Navegantes",
        "Palhoca",
        "Passo de Torres",
        "Penha",
        "Porto Belo",
        "Sao Francisco do Sul",
        "Tijucas"
    ],
    "Sergipe" => [
        "Aracaju",
        "Barra dos Coqueiros",
        "Brejo Grande",
        "Estancia",
        "Itaporanga d'Ajuda",
        "Pacatuba",
        "Pirambu"
    ],
    "Sao Paulo" => [
        "Caraguatatuba",
        "Cananeia",
        "Guaruja",
        "Ilha Comprida",
        "Ilhabela",
        "Iguape",
        "Itanhaem",
        "Mongagua",
        "Peruibe",
        "Praia Grande",
        "Sao Sebastiao",
        "Sao Vicente",
        "Santos",
        "Ubatuba"
    ],
    "Tocantins" => [
        "Palmas",
        "Araguaina",
        "Gurupi",
        "Porto Nacional",
        "Paraiso do Tocantins"
    ]
];
